DROP DATABASE IF EXISTS oopauth;
CREATE DATABASE oopauth DEFAULT CHARACTER SET utf8;
USE oopauth;

CREATE TABLE users(
	id			INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name		VARCHAR(75) NOT NULL,
	email		VARCHAR(75) NOT NULL,
	password	CHAR(32) NOT NULL
);